core/urls.py
from django.urls import path

from core.views.advisor import advisor_list, advisor_form, advisor_edit, advisor_edit_from_home, advisor_delete, advisor_form_home
from core.views.c_level import c_level_list, c_level_form, c_level_edit, c_level_delete
from core.views.company_domain import (
    company_domain_list, company_domain_delete, company_domain_edit,
    company_domain_form
)
from core.views.company_industry import (
    company_industry_list, company_industry_form, company_industry_edit,
    company_industry_delete
)
from core.views.funding import funding_list, funding_form, funding_edit, funding_delete
from core.views.region import region_form, region_list, region_edit, region_delete
from core.views.startup import startup_form, startup_list, startup_edit, startup_edit_from_home, startup_delete, startup_form_home
from core.views.match import (
    match_list, close_match, connect_with_startup, connect_with_advisor,
    add_match_file, del_match_file, get_match_files
)
from core.views.match_keys_points import match_keys_points_edit
from core.views.testimonials import testimonials_list, testimonials_form, testimonials_edit, testimonials_delete
from core.views.interest_expressed import interest_expressed_list, interest_expressed_form, interest_expressed_edit, \
    interest_expressed_delete, interest_expressed_set
from core.views.terms_conditions import termsconditions_list, termsconditions_form, termsconditions_edit, termsconditions_delete

app_name = "core"

urlpatterns = [
    path("region/", region_list, name="region_list"),
    path("region/add/", region_form, name="region_create"),
    path("region/edit/<int:pk>/", region_edit, name="region_edit"),
    path("region/delete/<int:pk>/", region_delete, name="region_delete"),

    path("company-domain/", company_domain_list, name="company_domain_list"),
    path("company-domain/add/", company_domain_form, name="company_domain_create"),
    path("company-domain/edit/<int:pk>/", company_domain_edit, name="company_domain_edit"),
    path("company-domain/delete/<int:pk>/", company_domain_delete, name="company_domain_delete"),

    path("company-industry/", company_industry_list, name="company_industry_list"),
    path("company-industry/add/", company_industry_form, name="company_industry_create"),
    path("company-industry/edit/<int:pk>/", company_industry_edit, name="company_industry_edit"),
    path("company-industry/delete/<int:pk>/", company_industry_delete, name="company_industry_delete"),

    path("funding/", funding_list, name="funding_list"),
    path("funding/add/", funding_form, name="funding_create"),
    path("funding/edit/<int:pk>/", funding_edit, name="funding_edit"),
    path("funding/delete/<int:pk>/", funding_delete, name="funding_delete"),

    path("c-level/", c_level_list, name="c_level_list"),
    path("c-level/add/", c_level_form, name="c_level_create"),
    path("c-level/edit/<int:pk>/", c_level_edit, name="c_level_edit"),
    path("c-level/delete/<int:pk>/", c_level_delete, name="c_level_delete"),

    path("match-keys-points/edit/", match_keys_points_edit, name="match_keys_points_edit"),

    path("startup/", startup_list, name="startup_list"),
    path("startup/add/", startup_form, name="startup_create"),
    path("startup/add/home", startup_form_home, name="startup_create_home"),
    path("startup/edit/<int:pk>/", startup_edit, name="startup_edit"),
    path("startup/edit/home/<int:pk>/", startup_edit_from_home, name="startup_edit_from_home"),
    path("startup/delete/<int:pk>/", startup_delete, name="startup_delete"),

    path("advisor/", advisor_list, name="advisor_list"),
    path("advisor/add/", advisor_form, name="advisor_create"),
    path("advisor/add/home/", advisor_form_home, name="advisor_create_home"),
    path("advisor/edit/<int:pk>/", advisor_edit, name="advisor_edit"),
    path("advisor/edit/home/<int:pk>/", advisor_edit_from_home, name="advisor_edit_from_home"),
    path("advisor/delete/<int:pk>/", advisor_delete, name="advisor_delete"),

    path("match/", match_list, name="match_list"),
    path("match/close/<int:pk>/", close_match, name="close_match"),
    path("match/connect_with_startup/<int:pk>/", connect_with_startup, name="connect_with_startup"),
    path("match/connect_with_advisor/<int:pk>/", connect_with_advisor, name="connect_with_advisor"),
    path("match/get_match_files/<int:pk>/", get_match_files, name="get_match_files"),
    path("match/del_match_file/<int:pk>/", del_match_file, name="del_match_file"),
    path("match/add_match_file/<int:pk>/", add_match_file, name="add_match_file"),

    path("testimonials/", testimonials_list, name="testimonials_list"),
    path("testimonials/add/", testimonials_form, name="testimonials_create"),
    path("testimonials/edit/<int:pk>/", testimonials_edit, name="testimonials_edit"),
    path("testimonials/delete/<int:pk>/", testimonials_delete, name="testimonials_delete"),

    path("interest-expressed/", interest_expressed_list, name="interest_expressed_list"),
    path("interest-expressed/add/", interest_expressed_form, name="interest_expressed_create"),
    path("interest-expressed/edit/<int:pk>/", interest_expressed_edit, name="interest_expressed_edit"),
    path("interest-expressed/delete/<int:pk>/", interest_expressed_delete, name="interest_expressed_delete"),
    path("interest_expressed/interest_expressed_set/", interest_expressed_set, name="interest_expressed_set"), 
    #path("interest_expressed/interest_expressed_set/<str:pk>/", interest_expressed_set, name="interest_expressed_set"),

    path("termsconditions/", termsconditions_list, name="termsconditions_list"),
    path("termsconditions/add/", termsconditions_form, name="termsconditions_create"),
    path("termsconditions/edit/<int:pk>/", termsconditions_edit, name="termsconditions_edit"),
    path("termsconditions/delete/<int:pk>/", termsconditions_delete, name="termsconditions_delete"),
]

matchProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("user.urls")),
    path("settings/", include("core.urls", namespace="core")),
    path("accounts/", include('allauth.urls')),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models/terms_conditions.py
from django.db import models
from django.core.validators import FileExtensionValidator


class TermsConditions(models.Model):
    name = models.CharField(max_length=100)
    upload_termsconditions = models.FileField(
        upload_to='uploads/terms_conditions/',
        validators=[
            FileExtensionValidator(allowed_extensions=['pdf'])
        ],
        null=True,
        blank=True
    )
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

core/forms/interest_expressed.py
from django import forms
from core.models.interest_expressed import InterestExpressed


class InterestExpressedForm(forms.ModelForm):
    class Meta:
        model = InterestExpressed
        fields = "__all__"
        widgets = {
            "reason_description": forms.Textarea(attrs={"class": "form-control", "cols": 80, "rows": 4}),
            "reason_i_know_one": forms.CheckboxInput(attrs={"class": "form-check"}),
            "reason_i_am_interested": forms.CheckboxInput(attrs={"class": "form-check"}),
            "reason_other": forms.CheckboxInput(attrs={"class": "form-check"}),
        }

core/forms/match.py
from django import forms

from core.models.match import MatchFiles

class MatchFilesForm(forms.ModelForm):
    class Meta:
        model = MatchFiles
        fields = ("file", )
        widgets = {
            "file": forms.FileInput(attrs={"class": "form-control"}),
        }

core/forms/terms_conditions.py
from django import forms
from core.models.terms_conditions import TermsConditions


class TermsConditionsForm(forms.ModelForm):
    class Meta:
        model = TermsConditions
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "upload_termsconditions": forms.FileInput(attrs={"class": "form-control", "accept": ".pdf"})
        }

core/views/advisor.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url as r, get_object_or_404

from core.forms.advisor import AdvisorForm
from core.models.advisor import AdvisorUser
from core.models.terms_conditions import TermsConditions
from core.views.mail import email_admin, email_startup_advisor_register, email_startup_advisor_active
from core.views.match import match_list_for_advisor_user_id, format_object
from user.forms import CustomRegisterForm, CustomChangeForm
from core.tools import count_points

User = get_user_model()


@login_required()
def advisor_list(request):
    if not request.user.is_staff:
        raise PermissionDenied

    advisors = AdvisorUser.objects.all()
    context = {"advisors": advisors}
    return render(request, 'core/advisor/advisor_list.html', context)


@login_required()
def advisor_form(request):
    if not request.user.is_staff:
        raise PermissionDenied

    user_form = CustomRegisterForm(request.POST or None)
    form = AdvisorForm(request.POST, request.FILES or None)
    terms_condition_actual = TermsConditions.objects.last()

    if request.method == "POST":

        if user_form.is_valid() and form.is_valid():
            try:
                django_user = user_form.save()
                form.save(user=django_user)

                messages.success(request, "Registry added successfully")
                return HttpResponseRedirect(r("core:advisor_list"))

            except IntegrityError:
                messages.error(request, "This email is already in use!")

    context = {
        "user_form": user_form,
        "form": form,
        "new": True,
        "terms_conditions": terms_condition_actual,
    }
    return render(request, "core/advisor/advisor_form.html", context)


def advisor_form_home(request):

    user_form = CustomRegisterForm(request.POST or None)
    form = AdvisorForm(request.POST, request.FILES or None)

    if request.method == "POST":


        if user_form.is_valid() and form.is_valid():
            try:
                django_user = user_form.save()
                advisor = form.save(user=django_user)

                formated_match_keys = format_object(advisor)

                count = count_points.countPoints(formated_match_keys)

                email_admin(
                    host=str(request.get_host()),
                    user_profile=advisor,
                    subject="New advisor registration",
                    cause="registration",
                    who_am_i=advisor.who_am_I.lower()
                )
                email_startup_advisor_register(user_email=django_user.email)

                advisor = form.save(commit=False, user=django_user)
                advisor.status = 1
                advisor.score = count
                advisor.save()

                messages.success(request, "Your submit is successfully")
                return HttpResponseRedirect(r("home"))
            except IntegrityError:
                messages.error(request, "This email is already in use!")
        else:
            messages.error(request, user_form.errors)

    return HttpResponseRedirect(r("home"))


@login_required()
def advisor_edit(request, pk):
    if not request.user.is_staff:
        raise PermissionDenied

    advisor = get_object_or_404(AdvisorUser, pk=pk)
    form = AdvisorForm(instance=advisor)
    user_form = CustomChangeForm(request.POST or None, instance=advisor.user_id)
    terms_condition_actual = TermsConditions.objects.last()

    if request.method == "POST":
        form = AdvisorForm(request.POST, request.FILES, instance=advisor)

        if user_form.is_valid() and form.is_valid():
            try:
                django_user = user_form.save()

                formated_match_keys = format_object(advisor)
                count = count_points.countPoints(formated_match_keys)

                advisor_id = form.save(commit=False, user=django_user)
                advisor_id.score = count
                advisor_id.save()
                messages.success(request, "Advisor Updated successfully")

                if advisor_id.status == 2:
                    email_startup_advisor_active(
                        user_email=django_user.email,
                        host=str(request.get_host())
                    )

                return HttpResponseRedirect(r("core:advisor_list"))

            except IntegrityError:
                messages.error(request, "This email is already in use!")

    context = {
        "form": form,
        "user_form": user_form,
        "terms_conditions": terms_condition_actual,
    }

    return render(request, "core/advisor/advisor_form.html", context)


@login_required()
def advisor_edit_from_home(request, pk):

    if request.method == 'GET':
        return HttpResponseRedirect(r("admin"))

    advisor = get_object_or_404(AdvisorUser, pk=pk)
    if not request.user == advisor.user_id:
        raise PermissionDenied

    form = AdvisorForm(request.POST, request.FILES, instance=advisor)
    user_form = CustomChangeForm(request.POST or None, instance=advisor.user_id)
    terms_condition_actual = TermsConditions.objects.last()

    if request.method == "POST":

        if advisor.status == 4:
            return HttpResponseRedirect(r("admin"))

        if user_form.is_valid() and form.is_valid():
            try:
                formated_match_keys = format_object(advisor)

                count = count_points.countPoints(formated_match_keys)

                django_user = user_form.save()
                advisor.status = 3

                advisor = form.save(commit=False, user=django_user)
                advisor.score = count
                advisor.save()

                email_admin(
                    host=str(request.get_host()),
                    user_profile=advisor,
                    subject="Advisor profile edit",
                    cause="update",
                    who_am_i=advisor.who_am_I.lower()
                )


                messages.success(request, "Advisor Updated successfully")
                return HttpResponseRedirect(r("admin"))

            except IntegrityError:
                messages.error(request, "This email is already in use!")

    context = {
        "form": form,
        "user_form": user_form,
        "terms_conditions": terms_condition_actual,
        "matches_list": match_list_for_advisor_user_id(request.user.id)
    }


    if advisor.status == 4:
        context['matches_list'] = []
        messages.error(request, 'User Inactive')

    return render(request, 'user/home_admin_dashboard.html', context)


@login_required()
def advisor_delete(request, pk):
    if not request.user.is_staff:
        raise PermissionDenied

    advisor = get_object_or_404(AdvisorUser, pk=pk)

    if request.method == 'POST':
        advisor.delete()
        messages.success(request, "Registry removed successfully")
        return HttpResponseRedirect(r('core:advisor_list'))

    context = {'object': advisor}
    return render(request, 'core/delete.html', context)

core/views/c_level.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url as r, get_object_or_404
from core.tools import update_points

from core.forms.auxiliary_tables import CLevelForm
from core.models.auxiliary_tables import CLevel


@login_required()
def c_level_list(request):
    if not request.user.is_staff:
        raise PermissionDenied

    c_level = CLevel.objects.all()
    context = {"c_level": c_level}
    return render(request, 'core/c_level/c_level_list.html', context)


@login_required()
def c_level_form(request):
    if not request.user.is_staff:
        raise PermissionDenied

    form = CLevelForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Registry added successfully")
            return HttpResponseRedirect(r("core:c_level_list"))

    context = {
        "form": form,
        "new": True
    }
    return render(request, "core/c_level/c_level_form.html", context)


@login_required()
def c_level_edit(request, pk):
    if not request.user.is_staff:
        raise PermissionDenied

    c_level = get_object_or_404(CLevel, pk=pk)
    form = CLevelForm(instance=c_level)

    if request.method == "POST":
        form = CLevelForm(request.POST, instance=c_level)
        if form.is_valid():
            form.save()
            update_points.updatePoints()
            messages.success(request, "Registry updated successfully")
            return HttpResponseRedirect(r("core:c_level_list"))

    context = {"form": form}
    return render(request, "core/c_level/c_level_form.html", context)


@login_required()
def c_level_delete(request, pk):
    if not request.user.is_staff:
        raise PermissionDenied

    c_level = get_object_or_404(CLevel, pk=pk)

    if request.method == 'POST':
        c_level.delete()
        messages.success(request, "Registry removed successfully")
        return HttpResponseRedirect(r('core:c_level_list'))

    context = {'object': c_level}
    return render(request, 'core/delete.html', context)

templates/core/interest_expressed/interest_expressed_form.html
{% extends 'base.html' %}

{% load static %}

{% block title_content %}
<!--img src="{% static 'img/executive.png' %}" width="40px" height="40px"-->
{% if new %} New {% else %} Edit {% endif %} Interest Expressed {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/forms_adjusts.css' %}">
<link rel="stylesheet" href="{% static 'css/modal_show_documents.css' %}">
{% endblock %}

{% block content %}

<a style="text-decoration: none; margin-left: 20px;" href="{% url 'core:interest_expressed_list' %}">
  <i class="fas fa-arrow-left fa-1x"></i>
</a>
<div class="col-12" id="interests_expressed">
  <form id="submit_form" action="." method="post" enctype="multipart/form-data" style="display: flex; flex-flow: row wrap; align-items: center;">
    {% csrf_token %}
    <div class="form-group col-md-6">
      <label for="name">Advisor</label>
      {{ form.advisor }}
    </div>
    <div class="form-group col-md-6">
      <label for="name">Startup</label>
      {{ form.startup }}
    </div>
    <div class="row form-group col-md-12">
      <label for="first_name">Must pick an option</label>
      <ul class="ml-4 mb-0 fa-ul text-muted">
        <li class="small">
          {{ form.reason_i_know_one }}<label style="margin-left: 10px; margin-top: 5px;">I know a great advisor for this startup</label>
        </li>
        <li class="small">
          {{ form.reason_i_am_interested }}<label style="margin-left: 10px; margin-top: 5px;">I'm personally interest in this startup</label>
        </li>
        <li class="small">
          {{ form.reason_other }}<label style="margin-left: 10px; margin-top: 5px;">Other</label>
        </li>
      </ul>
    </div>
    <div class="form-group col-md-12">
      <label for="description">Description</label>
      {{ form.reason_description }}
    </div>
    <div class="row col-12">
      <div class="form-group col-md-3" style="margin-left: -10px;">
        <input id="submit_button" class="btn btn-dark" type="submit" value="Submit" style="margin-left: 10px;">
      </div>
    </div>
  </form>
</div>
{% endblock %}

{% block script %}
<script>
  $(document).ready(function () {
    const div_i_know_one = document.getElementById("id_reason_i_know_one");
    div_i_know_one.setAttribute("class", "form-check form-check-inline");
    const div_i_am_interested = document.getElementById("id_reason_i_am_interested");
    div_i_am_interested.setAttribute("class", "form-check form-check-inline");
    const div_other = document.getElementById("id_reason_other");
    div_other.setAttribute("class", "form-check form-check-inline");
  })
</script>
{% endblock %}

templates/core/interest_expressed/interest_expressed_list.html
{% extends 'base.html' %}

{% load static %}

{% block title_content %} Interests Expressed List {% endblock %}

{% block css %} 
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}

<a style="text-decoration: none;" href="{% url 'core:interest_expressed_create' %}">
    <button type="button" class="btn btn-dark">Include</button>
</a>
<br/> <br/>

<div class="card">
    <div class="card-body">
      <table id="datatable" class="dataTable row-border" style="width:100%">
        <thead>
        <tr>
          <th>Advisor</th>
          <th>Startup</th>
          <th>Description</th>
          <th>Date & Time </th>
          <th data-orderable="false">Action</th>
        </tr>
        </thead>
        <tbody>
            {% for item in interests_expressed_list %}
                <tr>
                    <td>{{ item.advisor }}</td>
                    <td>{{ item.startup }}</td>
                    <td>{{ item.reason_description }}</td>
                    <td>{{ item.date|date:'m/d/Y H:i' }}</td>
                    <td>
                        <a href="{% url 'core:interest_expressed_edit' item.id %}" class="edit-btn">
                            <i class="fas fa-edit" style="color: black;"></i>
                        </a>
                        <a href="#" data-username="{{ item.advisor }}" data-url="{% url 'core:interest_expressed_delete' item.id %}" class="deleteinterestexpressed">
                          <i class="fas fa-trash" style="color: black;"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

<div class="modal fade" id="deleteinterestexpressed" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Delete Interest Expressed from <span id="username"></span>?</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
            Are you sure you want to delete this Interest Expressed?
        </div>
        <div class="modal-footer" id="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form method="POST">
          {% csrf_token %}
            <button type="submit" class="btn btn-secondary">Delete</button>
          </form>
        </div>
      </div>
    </div>
</div>

{% endblock %}

{% block script %}
  
{% include 'datatables.html' %}

<script>
  
$(document).ready(function() {
    $('a.deleteinterestexpressed').on( "click", function() {
        event.preventDefault();
        $('#deleteinterestexpressed form').attr('action', $(this).data("url"));
        $('#deleteinterestexpressed #username').text($(this).data("username"));
        $('#deleteinterestexpressed').modal('show');
    });
});

</script>

{% endblock %}