core/urls.py
from django.urls import path

from core.views.advisor import advisor_list, advisor_form, advisor_edit, advisor_edit_from_home, advisor_delete, advisor_form_home
from core.views.c_level import c_level_list, c_level_form, c_level_edit, c_level_delete
from core.views.company_domain import (
    company_domain_list, company_domain_delete, company_domain_edit,
    company_domain_form
)
from core.views.company_industry import (
    company_industry_list, company_industry_form, company_industry_edit,
    company_industry_delete
)
from core.views.funding import funding_list, funding_form, funding_edit, funding_delete
from core.views.region import region_form, region_list, region_edit, region_delete
from core.views.startup import startup_form, startup_list, startup_edit, startup_edit_from_home, startup_delete, startup_form_home
from core.views.match import (
    match_list, close_match, connect_with_startup, connect_with_advisor,
    add_match_file, del_match_file, get_match_files
)
from core.views.match_keys_points import match_keys_points_edit
from core.views.testimonials import testimonials_list, testimonials_form, testimonials_edit, testimonials_delete
from core.views.interest_expressed import interest_expressed_list, interest_expressed_form, interest_expressed_edit, \
    interest_expressed_delete, interest_expressed_set
from core.views.terms_conditions import termsconditions_list, termsconditions_form, termsconditions_edit, termsconditions_delete

app_name = "core"

urlpatterns = [
    path("region/", region_list, name="region_list"),
    path("region/add/", region_form, name="region_create"),
    path("region/edit/<int:pk>/", region_edit, name="region_edit"),
    path("region/delete/<int:pk>/", region_delete, name="region_delete"),

    path("company-domain/", company_domain_list, name="company_domain_list"),
    path("company-domain/add/", company_domain_form, name="company_domain_create"),
    path("company-domain/edit/<int:pk>/", company_domain_edit, name="company_domain_edit"),
    path("company-domain/delete/<int:pk>/", company_domain_delete, name="company_domain_delete"),

    path("company-industry/", company_industry_list, name="company_industry_list"),
    path("company-industry/add/", company_industry_form, name="company_industry_create"),
    path("company-industry/edit/<int:pk>/", company_industry_edit, name="company_industry_edit"),
    path("company-industry/delete/<int:pk>/", company_industry_delete, name="company_industry_delete"),

    path("funding/", funding_list, name="funding_list"),
    path("funding/add/", funding_form, name="funding_create"),
    path("funding/edit/<int:pk>/", funding_edit, name="funding_edit"),
    path("funding/delete/<int:pk>/", funding_delete, name="funding_delete"),

    path("c-level/", c_level_list, name="c_level_list"),
    path("c-level/add/", c_level_form, name="c_level_create"),
    path("c-level/edit/<int:pk>/", c_level_edit, name="c_level_edit"),
    path("c-level/delete/<int:pk>/", c_level_delete, name="c_level_delete"),

    path("match-keys-points/edit/", match_keys_points_edit, name="match_keys_points_edit"),

    path("startup/", startup_list, name="startup_list"),
    path("startup/add/", startup_form, name="startup_create"),
    path("startup/add/home", startup_form_home, name="startup_create_home"),
    path("startup/edit/<int:pk>/", startup_edit, name="startup_edit"),
    path("startup/edit/home/<int:pk>/", startup_edit_from_home, name="startup_edit_from_home"),
    path("startup/delete/<int:pk>/", startup_delete, name="startup_delete"),

    path("advisor/", advisor_list, name="advisor_list"),
    path("advisor/add/", advisor_form, name="advisor_create"),
    path("advisor/add/home/", advisor_form_home, name="advisor_create_home"),
    path("advisor/edit/<int:pk>/", advisor_edit, name="advisor_edit"),
    path("advisor/edit/home/<int:pk>/", advisor_edit_from_home, name="advisor_edit_from_home"),
    path("advisor/delete/<int:pk>/", advisor_delete, name="advisor_delete"),

    path("match/", match_list, name="match_list"),
    path("match/close/<int:pk>/", close_match, name="close_match"),
    path("match/connect_with_startup/<int:pk>/", connect_with_startup, name="connect_with_startup"),
    path("match/connect_with_advisor/<int:pk>/", connect_with_advisor, name="connect_with_advisor"),
    path("match/get_match_files/<int:pk>/", get_match_files, name="get_match_files"),
    path("match/del_match_file/<int:pk>/", del_match_file, name="del_match_file"),
    path("match/add_match_file/<int:pk>/", add_match_file, name="add_match_file"),

    path("testimonials/", testimonials_list, name="testimonials_list"),
    path("testimonials/add/", testimonials_form, name="testimonials_create"),
    path("testimonials/edit/<int:pk>/", testimonials_edit, name="testimonials_edit"),
    path("testimonials/delete/<int:pk>/", testimonials_delete, name="testimonials_delete"),

    path("interest-expressed/", interest_expressed_list, name="interest_expressed_list"),
    path("interest-expressed/add/", interest_expressed_form, name="interest_expressed_create"),
    path("interest-expressed/edit/<int:pk>/", interest_expressed_edit, name="interest_expressed_edit"),
    path("interest-expressed/delete/<int:pk>/", interest_expressed_delete, name="interest_expressed_delete"),
    path("interest_expressed/interest_expressed_set/", interest_expressed_set, name="interest_expressed_set"), 
    #path("interest_expressed/interest_expressed_set/<str:pk>/", interest_expressed_set, name="interest_expressed_set"),

    path("termsconditions/", termsconditions_list, name="termsconditions_list"),
    path("termsconditions/add/", termsconditions_form, name="termsconditions_create"),
    path("termsconditions/edit/<int:pk>/", termsconditions_edit, name="termsconditions_edit"),
    path("termsconditions/delete/<int:pk>/", termsconditions_delete, name="termsconditions_delete"),
]

matchProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("user.urls")),
    path("settings/", include("core.urls", namespace="core")),
    path("accounts/", include('allauth.urls')),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('dashboard/', views.admin, name='admin'),
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('user/list', views.user_list, name='list'),
    path('user/register/', views.users_register, name='register'),
    path('user/delete/<int:pk>', views.users_delete, name='delete'),
    path('user/edit/<int:pk>', views.users_edit, name='edit'),
]

core/models/advisor.py
import os

from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from django.db import models

from core.models.auxiliary_tables import Region, CLevel, CompanyIndustry

User = get_user_model()

STATUS = (
    (0, "New"),
    (1, "Pending Review"),
    (2, "Active"),
    (3, "Pending Update"),
    (4, "Inactive")
)

HOURS_INVEST = (
    (1, "1-2hrs/week"),
    (2, "3-5hrs/week"),
    (3, "5+hrs/week")
)

START_AT = (
    (1, "Immediately"),
    (2, "Between 1-2 months"),
    (3, "3+ months")
)

FRACTIONAL_C_LEVEL = (
    (False, "No"),
    (True, "Yes")
)


def file_path(instance, filename: str) -> str:
    """
    This function will save the user files
    @param instance: AdminUser, AdvisorUser or StartupUser
    @param filename: a string with name from the file
    @return: like 'uploads/Admin/9_rigel_cobb/profile_picture.png'
    """
    _, file_extension = os.path.splitext(filename)

    username = instance.user_id.get_full_name().replace(" ", "_").lower()

    dir_name = f'{instance.user_id_id}_{username}'
    file_name = 'document' if file_extension == '.pdf' else 'profile_picture'

    return f'uploads/{instance.who_am_I}/{dir_name}/{file_name}{file_extension}'


class AdvisorUser(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS, default=1)
    who_am_I = models.CharField(max_length=20, default="Advisor", blank=True)
    title = models.CharField(max_length=144)
    linkedin = models.CharField(max_length=50)
    commerce_tech = models.BooleanField()
    commerce_tech_user = models.ManyToManyField(
        CompanyIndustry,
        related_name="advisor_commerce_tech_user",
        blank=True
    )
    fintech = models.BooleanField()
    fintech_user = models.ManyToManyField(
        CompanyIndustry,
        related_name="advisor_fintech_user",
        blank=True
    )
    gtm_strategy = models.BooleanField(default=False)
    domestic = models.BooleanField()
    international = models.BooleanField()
    tech = models.BooleanField()
    fundraising = models.BooleanField()
    human_capital = models.BooleanField()
    regions_international = models.ManyToManyField(
        Region,
        related_name="advisor_regions_international",
        blank=True
    )
    description = models.TextField()
    terms_conditions = models.BooleanField()
    regions_user = models.ManyToManyField(Region, related_name="advisor_regions_user")
    highlight_profile_1 = models.CharField(max_length=500, default="")
    highlight_profile_2 = models.CharField(max_length=500, default="")
    highlight_profile_3 = models.CharField(max_length=500, default="")
    hours_invest = models.IntegerField(choices=HOURS_INVEST)
    fractional_c_level = models.BooleanField(choices=FRACTIONAL_C_LEVEL)
    c_level_user = models.ManyToManyField(CLevel, related_name="advisor_c_level_user", blank=True)
    start_at = models.IntegerField(choices=START_AT)
    upload_resume = models.FileField(
        upload_to=file_path,
        validators=[
            FileExtensionValidator(allowed_extensions=["pdf"])
        ],
        null=True,
        blank=True,
    )
    upload_profile_picture = models.ImageField(
        upload_to=file_path,
        null=True,
        blank=True
    )
    enable_match = models.BooleanField()
    score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, default=1)

    def __str__(self):
        return f"{self.user_id.get_full_name()}"

    def save(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            this = AdvisorUser.objects.get(id=self.id)

            if this.upload_resume != self.upload_resume:
                this.upload_resume.delete(save=False)

            if this.upload_profile_picture != self.upload_profile_picture:
                this.upload_profile_picture.delete(save=False)

        except Exception as e:
            print(e)
            pass  # when new photo then we do nothing, normal case
        super(AdvisorUser, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # delete files from personal folder before delete your register
        try:
            if self.upload_resume:
                self.upload_resume.delete(save=False)

            if self.upload_profile_picture:
                self.upload_profile_picture.delete(save=False)

        except Exception as e:
            print(e)
            pass
        super(AdvisorUser, self).delete(*args, **kwargs)

user/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models.advisor import file_path

User = get_user_model()


class AdminUser(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    who_am_I = models.CharField(max_length=20, default="Admin", blank=True)
    permissions = models.BooleanField(default=False)
    position = models.CharField(max_length=30)
    upload_profile_picture = models.ImageField(
        upload_to=file_path,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.user_id.get_full_name()

    def save(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            this = AdminUser.objects.get(id=self.id)

            if this.upload_profile_picture != self.upload_profile_picture:
                this.upload_profile_picture.delete(save=False)

        except Exception as e:
            print(e)
            pass  # when new photo then we do nothing, normal case
        super(AdminUser, self).save(*args, **kwargs)

user/forms.py
from allauth.account.models import EmailAddress
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import widgets, ModelForm, TextInput

from core.forms.advisor import ClearableFileInputCustom
from user.models import AdminUser

User = get_user_model()


class CustomRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget = widgets.TextInput(attrs={"class": "form-control"})
        self.fields["last_name"].widget = widgets.TextInput(attrs={"class": "form-control"})
        self.fields["email"].widget = widgets.EmailInput(attrs={"class": "form-control"})
        self.fields['password1'].widget = widgets.PasswordInput(attrs={"class": "form-control"})
        self.fields['password2'].widget = widgets.PasswordInput(attrs={"class": "form-control"})
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        self.fields["email"].required = True

    def save(self, commit=True, who_am_i=None):
        user = super().save(commit=False)
        user.username = self.cleaned_data["email"]
        if who_am_i == "Admin":
            user.is_staff = True
        user.save()
        return user


class CustomChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget = widgets.TextInput(attrs={"class": "form-control"})
        self.fields["last_name"].widget = widgets.TextInput(attrs={"class": "form-control"})
        self.fields["email"].widget = widgets.EmailInput(attrs={"class": "form-control"})
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        self.fields["email"].required = True

    def save(self, commit=True):
        try:

            this = User.objects.get(id=self.instance.id)
            user = super().save(commit=False)

            if this.first_name != self.instance.first_name:
                user.first_name = self.cleaned_data["first_name"]

            if this.last_name != self.instance.last_name:
                user.last_name = self.cleaned_data["last_name"]

            if this.email != self.instance.email:
                user.email = self.cleaned_data["email"]
                user.username = self.cleaned_data["email"]

                if EmailAddress.objects.filter(user=this, verified=True).exists():
                    old_email_login = EmailAddress.objects.get(user=this)
                    old_email_login.delete()

            user.save()

            return user

        except Exception as e:
            print(e)
            pass


class RegisterAdminForm(ModelForm):
    class Meta:
        model = AdminUser
        exclude = ["user_id", "who_am_I", "permissions"]
        widgets = {
            "position": TextInput(attrs={"class": "form-control"}),
            "upload_profile_picture": ClearableFileInputCustom(attrs={"class": "form-control"}),
        }

    def save(self, commit=False, user=None):

        self.instance.user_id = user
        advisor = super(RegisterAdminForm, self).save()

        if commit:
            advisor.save()

        return advisor

templates/user/home_admin_dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block title_content %}
{% if not user.is_staff %}
{% if form.who_am_I.value == "Advisor" %}
List of Startups
{% else %}
List of Advisors
{% endif %}
{% else %}
Dashboard
{% endif %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet" href="{% static 'css/forms_adjusts_home.css' %}">
{% endblock %}

{% block content %}

{% if user.is_staff %}
<div class="row">
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box" style="background-color: #ffbbbb;">
      <div class="inner">
        <h3>{{ matches_list|length }}</h3>
        <p class="text-muted mb-0">Matches</p>
      </div>
      <div class="icon">
        <i class="fas fa-user-friends"></i>
      </div>
      <a href="{% url 'core:match_list' %}" class="small-box-footer">
        Show <i class="fas fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box" style="background-color: #bbffff;">
      <div class="inner">
        <h3>{{ matches_closed_list|length }}</h3>
        <p class="text-muted mb-0">Matches Success</p>
      </div>
      <div class="icon">
        <i class="fas fa-handshake"></i>
      </div>
      <a href="{% url 'core:match_list' %}" class="small-box-footer">
        Show <i class="fas fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box" style="background-color: #bbdddd;">
      <div class="inner">
        <h3>{{ matches_interest_expressed_list|length }}</h3>
        <p class="text-muted mb-0">Match Interest Expressed</p>
      </div>
      <div class="icon">
        <i class="fas fa-handshake"></i>
      </div>
      <a href="{% url 'core:match_list' %}" class="small-box-footer">
        Show <i class="fas fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box" style="background-color: #bbaaaa;">
      <div class="inner">
        <h3>{{ interest_expressed_list|length }}</h3>
        <p class="text-muted mb-0">Interest Expressed</p>
      </div>
      <div class="icon">
        <i class="fas fa-handshake"></i>
      </div>
      <a href="{% url 'core:interest_expressed_list' %}" class="small-box-footer">
        Show <i class="fas fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box" style="background-color: #bbffbb;">
      <div class="inner">
        <h3>{{ startups|length }}</h3>
        <p class="text-muted mb-0"> Registered Startups </p>
      </div>
      <div class="icon">
        <i class="fas fa-rocket"></i>
      </div>
      <a href="{% url 'core:startup_list' %}" class="small-box-footer">
        Show <i class="fas fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box" style="background-color: #bbbbff;">
      <div class="inner">
        <h3>{{ advisors|length }}</h3>
        <p class="text-muted mb-0"> Registered Advisors </p>
      </div>
      <div class="icon">
        <i class="fas fa-user-tie"></i>
      </div>
      <a href="{% url 'core:advisor_list' %}" class="small-box-footer">
        Show <i class="fas fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>
  <!-- ./col -->
</div>
<!-- /.row -->

<!-- /.card -->
{% endif %}

{% if not user.is_staff %}
{% if form.who_am_I.value == "Startup" %}
{% with "formstartup" as form_id %}
{% include 'modal_startup.html' %}
{% endwith %}
{% include 'user/startup_view_dashboard_cards.html' %}
{% else %}
{% with "formadvisor" as form_id %}
{% include 'modal_advisor.html' %}
{% endwith %}
{% include 'user/advisor_view_dashboard_cards.html' %}
{% endif %}
{% endif %}

{% include 'modal_about.html' %}

{% include 'modal_express_interest.html' %}

{% include 'modal_crop_picture.html' %}

{% endblock %}

{% block script %}

{% if user.is_staff %}
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- hidden values -->
<input type="hidden" id="num_startups" name="variable" value="{{ startups|length }}">
<input type="hidden" id="num_advisors" name="variable" value="{{ advisors|length }}">
<input type="hidden" id="num_matches" name="variable" value="{{ matches_list|length }}">
<!-- end hidden values -->

<script>
  $(function () {
    /* ChartJS
     * -------
     * Here we will create a few charts using ChartJS
     */

    var num_startups = document.getElementById("num_startups").value;
    var num_advisors = document.getElementById("num_advisors").value;
    var num_matches = document.getElementById("num_matches").value;
    //-------------
    //- DONUT CHART -
    //-------------
    // Get context with jQuery - using jQuery's .get() method.
    var donutChartCanvas = $('#donutChart').get(0).getContext('2d')
    var donutData = {
      labels: [
        'Startups',
        'Advisors',
      ],
      datasets: [
        {
          data: [num_startups, num_advisors],
          backgroundColor: ['#f56954', '#00a65a'],
        }
      ]
    }
    var donutOptions = {
      maintainAspectRatio: false,
      responsive: true,
    }
    //Create pie or douhnut chart
    // You can switch between pie and douhnut using the method below.
    new Chart(donutChartCanvas, {
      type: 'doughnut',
      data: donutData,
      options: donutOptions
    })

    //-------------
    //- PIE CHART -
    //-------------
    // Get context with jQuery - using jQuery's .get() method.
    var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
    var pieData = donutData;
    var pieOptions = {
      maintainAspectRatio: false,
      responsive: true,
    }
    //Create pie or douhnut chart
    // You can switch between pie and douhnut using the method below.
    new Chart(pieChartCanvas, {
      type: 'pie',
      data: pieData,
      options: pieOptions
    })
  })

</script>

{% endif %}

<script>

  const list = document.querySelector("#display-list");
  const grid = document.querySelector("#display-grid");
  const cardsList = document.querySelector("#cards-display-list");
  const cardsGrid = document.querySelector("#cards-display-grid");

  const changeList = () => {
    list.style.display = "inline";
    grid.style.display = "none";
    cardsList.style.display = "none";
    cardsGrid.style.display = "inline";
  }
  const changeGrid = () => {
    list.style.display = "none";
    grid.style.display = "inline";
    cardsList.style.display = "inline";
    cardsGrid.style.display = "none";
  }
  document.querySelector("#display-list").addEventListener("click", changeGrid);
  document.querySelector("#display-grid").addEventListener("click", changeList);

</script>

<script>

  // Startup and Advisor form
  function FormControl(formid) {
    const _form = document.querySelector("#" + formid);
    const _fintech = _form.querySelector('#id_fintech');
    const _fintech_user = _form.querySelector("#fintech_user");
    const _commerce_tech = _form.querySelector('#id_commerce_tech');
    const _commerce_tech_user = _form.querySelector("#commerce_tech_user");
    const _international = _form.querySelector('#id_international');
    const _international_regions = _form.querySelector("#international_regions");
    const _human_capital = _form.querySelector('#id_human_capital');
    const _human_capital_users = _form.querySelector("#human_capital_users");



    _fintech.onclick = () => {
      if (_fintech.checked) {
        _fintech_user.style.display = "inline";
      } else {
        _fintech_user.style.display = "none";
        const _check = $("#" + formid).find('input[name="fintech_user"]').get();
        _check.forEach(element => {
          element.checked = false;
        });
      }
    }

    _commerce_tech.onclick = () => {

      if (_commerce_tech.checked) {
        _commerce_tech_user.style.display = "inline";
      } else {
        _commerce_tech_user.style.display = "none";
        const _check = $("#" + formid).find('input[name="commerce_tech_user"]').get();
        _check.forEach(element => {
          element.checked = false;
        });
      }

    }

    _international.onclick = () => {

      if (_international.checked) {
        _international_regions.style.display = "inline";
      } else {
        _international_regions.style.display = "none";
        const _check = $("#" + formid).find('input[name="regions_international"]').get();
        _check.forEach(element => {
          element.checked = false;
        });
      }

    }

    _human_capital.onclick = () => {

      if (_human_capital.checked) {
        _human_capital_users.style.display = "inline";
      } else {
        _human_capital_users.style.display = "none";
        const _check = $("#" + formid).find('input[name="c_level_user"]').get();
        _check.forEach(element => {
          element.checked = false;
        });
      }

    }

    const _div_fintech_user = _form.querySelector("#id_fintech_user");
    _div_fintech_user.className += ". row";
    const _div_commerce_tech_user = _form.querySelector("#id_commerce_tech_user");
    _div_commerce_tech_user.className += ". row";
    const _div_regions_user = _form.querySelector("#id_regions_user");
    _div_regions_user.className += ". row";
    const _div_regions_international = _form.querySelector("#id_regions_international");
    _div_regions_international.className += ". row";
    const _div_c_level_user = _form.querySelector("#id_c_level_user");
    _div_c_level_user.className += ". row";

    // Cropper
    // this is to get different input and img from startup and advisor
    const _input_upload_profile_picture = _form.querySelector("#id_upload_profile_picture");
    _input_upload_profile_picture.className += " pic_" + formid;
    const _chosenImage = _form.querySelector("#chosen-image");
    _chosenImage.className += " img_" + formid;

    let uploadButton = document.getElementsByClassName("pic_" + formid)[0];
    let chosenImage = document.getElementsByClassName("img_" + formid)[0];
    let result = document.querySelector('.result');
    let save = document.querySelector('.save');
    let cropped = document.querySelector('.cropped');
    let cropper = '';

    uploadButton.onchange = () => {
      let reader = new FileReader();
      reader.onload = () => {
        $('#modal_crop_picture').modal('show');
        let img = document.createElement('img');
        img.id = 'image';
        img.src = reader.result;
        // clean result before
        result.innerHTML = '';
        // append new image
        result.appendChild(img);
        // show save btn and options
        save.classList.remove('hide');
        // init cropper
        cropper = new Cropper(img);
      }
      reader.readAsDataURL(uploadButton.files[0]);
      // save on click
      save.addEventListener('click', async (e) => {
        e.preventDefault();
        // get result to data uri
        let imgSrc = cropper.getCroppedCanvas({
          width: 400,
          height: 400
        }).toDataURL();
        // show image cropped
        let img = document.createElement('img');
        img.id = 'image';
        img.src = imgSrc;

        fetch(imgSrc)
          .then(res => res.blob())
          .then(blob => {
            let container = new DataTransfer();
            let file = new File([blob], "img___.png", { type: "image/png", lastModified: new Date().getTime() });

            container.items.add(file);

            console.log(uploadButton.files);
            uploadButton.files = container.files;
            console.log(uploadButton.files);

          });

        chosenImage.setAttribute("src", imgSrc);
        $('#modal_crop_picture').modal('hide');
      });
    }
    // end Cropper

    const button1 = _form.querySelector("#togglePass1");
    if (button1 != null) {
      const password1 = _form.querySelector("#id_password1");
      button1.addEventListener('click', togglePass1);

      function togglePass1() {
        if (password1.type == "password") {
          password1.type = "text";
          button1.innerHTML = '<i class="fas fa-eye-slash"></i>';
        } else {
          password1.type = "password";
          button1.innerHTML = '<i class="fas fa-eye"></i>';
        }
      }
    }


    const button2 = _form.querySelector("#togglePass2");

    if (button2 != null) {
      const password2 = _form.querySelector("#id_password2");
      button2.addEventListener('click', togglePass2);

      function togglePass2() {
        if (password2.type == "password") {
          password2.type = "text";
          button2.innerHTML = '<i class="fas fa-eye-slash"></i>';
        } else {
          password2.type = "password";
          button2.innerHTML = '<i class="fas fa-eye"></i>';
        }
      }
    }
  }
</script>
{% if not user.is_staff %}
{% if form.who_am_I.value == "Startup" %}
<script>
  const startup_control = FormControl("formstartup");
</script>
{% else %}
<script>
  const advisor_control = FormControl("formadvisor");
</script>
{% endif %}
{% endif %}

{% endblock %}